# Generated by Django 4.2.19 on 2025-02-27 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_books_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('authors', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('preview_link', models.URLField(blank=True, null=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('categories', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleBookFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googlebooks.googlebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book')},
            },
        ),
        migrations.AddField(
            model_name='googlebook',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_google_books', through='googlebooks.GoogleBookFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GoogleBookReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read', models.DateTimeField(auto_now=True)),
                ('progress', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='googlebooks.googlebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_read'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
