# Generated by Django 4.2.19 on 2025-02-25 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('QUICK_READ', 'Quick Read'), ('EXPLORER', 'Explorer'), ('BOOKWORM', 'Bookworm')], max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_books_per_month', models.IntegerField(default=-1)),
                ('max_downloads', models.IntegerField(default=-1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptiontier')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
