# Generated by Django 4.2.19 on 2025-03-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_usersubscription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontier',
            name='currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso'), ('USD', 'US Dollar')], default='PHP', max_length=3),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='duration',
            field=models.CharField(choices=[('7D', '7 Days'), ('LT', 'Lifetime')], default='7D', max_length=2),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='payment_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='max_books_per_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='max_downloads',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptiontier',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
