# Generated by Django 4.2.19 on 2025-03-26 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptiontier_currency_subscriptiontier_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptiontier',
            name='max_books_per_month',
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='book_limit',
            field=models.IntegerField(default=10, help_text='Lifetime book access limit'),
            preserve_default=False,
        ),
    ]
