# Generated by Django 4.2.19 on 2025-02-25 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_google_books_id_book_open_library_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='open_library_id',
            new_name='google_books_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='number_of_pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='subjects',
        ),
    ]
