# Generated by Django 4.2.19 on 2025-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_open_library_id_book_google_books_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='google_books_id',
            new_name='google_books_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='preview_link',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.TextField(blank=True),
        ),
    ]
